-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 11:24:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projeto` DEFAULT CHARACTER SET utf8 ;
USE `Projeto` ;

-- -----------------------------------------------------
-- Table `Projeto`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`));


-- -----------------------------------------------------
-- Table `Projeto`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto`.`servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idServico`));


-- -----------------------------------------------------
-- Table `Projeto`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto`.`vaga` (
  `idVaga` INT NOT NULL AUTO_INCREMENT,
  `numero` DECIMAL NOT NULL,
  `fkServico` INT NOT NULL,
  `livre` TINYINT not null,
  PRIMARY KEY (`idVaga`),
    FOREIGN KEY (`fkServico`)
    REFERENCES `Projeto`.`servico` (`idServico`));



-- -----------------------------------------------------
-- Table `Projeto`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto`.`veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `fkCliente` INT NULL,
  PRIMARY KEY (`idVeiculo`),
    FOREIGN KEY (`fkCliente`)
    REFERENCES `Projeto`.`cliente` (`idCliente`));





-- -----------------------------------------------------
-- Table `Projeto`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `dataInicial` DATETIME NOT NULL,
  `dataSaida` DATETIME NULL,
  `fkVeiculo` INT NOT NULL,
  `fkVaga` INT NOT NULL,
  `valorTotal` FLOAT NULL,
  PRIMARY KEY (`idVenda`),
      FOREIGN KEY (`fkVeiculo`)
    REFERENCES `Projeto`.`veiculo` (`idVeiculo`),
    FOREIGN KEY (`fkVaga`)
    REFERENCES `Projeto`.`vaga` (`idVaga`));



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
