Algoritmo "EXERCICIO 5.2"
Var
nomeAluno : caracter
media,n1,n2,n3 : real
Inicio
escreval ("digite o nome do(a) aluno(a)")
leia(nomeAluno)
escreval("digite a primeira nota :")
leia(n1)
escreval("digite a segunda nota :")
leia(n2)
escreval("digite a terceira nota :")
leia(n3)
media<-(n1+n2+n3)/3
escreva("o(a) aluno(a) " + nomeAluno)
escreva(" obteve a media : ")
escreval(media)
Fimalgoritmo