Algoritmo "semnome"
Var
nomeAluno: caractere
nota1, nota2, nota3, media: real
Inicio
escreval("digite o nome do aluno : ")
leia(nomeAluno)
escreval("digite a nota 1 ")
leia(nota1)
escreval("digite a nota 2 ")
leia(nota2)
escreval("digite a nota 3 ")
leia(nota3)
media<- (nota1+nota2+nota3) / 3
escreva("o aluno " + nomeAluno)
escreva(" , obteve a media : ")
escreval(media)
Fimalgoritmo