Algoritmo "i"
Var
nome:caracter
n1, n2, n3, media : real
i : inteiro
Inicio
para i de 0 ate 3 faca
escreva("escreva o nome do aluno")
leia(nome)
escreval("digite nota1 :")
leia(n1)
escreval("digite nota2 :")
leia(n2)
escreval("digite nota3 :")
leia(n3)
media<-(n1+n2+n3)/3
se(media>=6.9)entao
escreval("aprovado")
senao
se(media<5)entao
escreval("reprovado")
senao
escreval("recuperacao")
fimse
Fimalgoritmo
fimse
i<-i+1
fimalgoritmo